# Generated by Django 4.2.7 on 2024-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembling', models.IntegerField(verbose_name='Кол-во коробов для сборки')),
                ('transported_pallet', models.IntegerField(verbose_name='Перемещение паллет')),
                ('coming_car', models.IntegerField(verbose_name='Выгрузка')),
                ('out_car', models.IntegerField(verbose_name='Загрузка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Информацию',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
